language: php
sudo: false

after_success:
    - mkdir build
    - mv * build
    - tar -czf package.tgz build
    - export SSHPASS='rAb@2Ufr3Xes!Uf'
    - sshpass -e scp package.tgz softdev@162.209.122.251:/var/www/html/testci
    
